const { smpoo, TUtil, tEcho, tCheckType, tDate, tVerifi, tPinyin } = require('../lib/index.esm');

const __tmpEncode__ = TUtil.encode.toUniCode('tFrameV9 平台');
// const __tmpWxNickCode__ = TUtil.encode.wechatNick('微信昵称"特殊字" ℃');
const _currTdate = tDate();

module.exports = {
	desc: {
		'TUtil.decode.toStr': '参数 [sep] 仅当 toStr的首个参数为字符串时有效，用于指定分隔该字符串的符号。',
		'tDate': `完整格式化字符串为：yyyy-mm-dd hh:mi:ss.ms [年-月-日 时:分:秒.毫秒]\n以下用例假设当前时间为：'${tDate().format('yyyy-mm-dd hh:mi:ss.ms')}'`,
		'tDate().formatAsWorld': '更多区域语言标记，参考 [Intl page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locale_identification_and_negotiation)',
		'tDate().toNumber': '仅当首个参数为 True 时，可以自定义数字模板'
	},
	case: [
		['TUtil.inBrowser', TUtil.inBrowser],
		['TUtil.inSvr', TUtil.inSvr],
		['TUtil.NUM_TO_STR', TUtil.NUM_TO_STR],
		[
			['TUtil.encode.toUniCode', TUtil.encode.toUniCode, 'tFrameV9 平台'],
			['TUtil.encode.wechatNick', TUtil.encode.wechatNick, __tmpEncode__, '微信昵称"特殊字" ℃'],
			['TUtil.decode.toStr', TUtil.decode.toStr, __tmpEncode__],
			['TUtil.decode.toStr ', TUtil.decode.toStr, __tmpEncode__, '-']
		],
		[
			['tCheckType', tCheckType, 'abc'],
			['tCheckType', tCheckType, 2],
			['tCheckType', tCheckType, true],
			['tCheckType', tCheckType, new Date()],
			['tCheckType', tCheckType, [1, 2, 3]],
			['tCheckType', tCheckType, {key: 'abc'}],
			['tCheckType', tCheckType, new Map()],
			['tCheckType', tCheckType, new Set()],
			['tCheckType', tCheckType, new WeakMap()],
			['tCheckType', tCheckType, new WeakSet()],
			['tCheckType', tCheckType, new Uint8Array()],
			['tCheckType', tCheckType, new Uint16Array()],
			['tCheckType', tCheckType, new Uint32Array()],
			'...'
		],
		[
			['tDate', tDate],
			['tDate', tDate, '2020-12-31'],
			['tDate', tDate, 1609372800000],
			['tDate', tDate, 2021, 4],
			['tDate', tDate, 2021, 4, 2],
			['tDate', tDate, 2021, 4, 2, 12, 0, 0],
			['tDate().isLeap', _currTdate.isLeap],
			['tDate().abs', _currTdate.abs],
			['tDate().year', _currTdate.year],
			['tDate().month', _currTdate.month],
			['tDate().day', _currTdate.day],
			['tDate().hour', _currTdate.hour],
			['tDate().millisecond', _currTdate.millisecond],
			['tDate().week', _currTdate.week],
			['tDate().quarter', _currTdate.quarter],
			['tDate().solar', _currTdate.solar],
			['tDate().sign', _currTdate.sign],
			['tDate().animal', _currTdate.animal],
			['tDate().indexOfQuarter', _currTdate.indexOfQuarter],
			['tDate().indexOfYear', _currTdate.indexOfYear],
			['tDate().daysOfMonth', _currTdate.daysOfMonth],
			['tDate().daysOfQuarter', _currTdate.daysOfQuarter],
			['tDate().daysOfYear', _currTdate.daysOfYear],
			['tDate().ratioOfWeek', _currTdate.ratioOfWeek],
			['tDate().ratioOfMonth', _currTdate.ratioOfMonth],
			['tDate().ratioOfQuarter', _currTdate.ratioOfQuarter],
			['tDate().ratioOfYear', _currTdate.ratioOfYear],
			['tDate().weekOfMonth', _currTdate.weekOfMonth],
			['tDate().weekOfYear', _currTdate.weekOfYear],
			['tDate().tiangan', _currTdate.tiangan],
			[`tDate('2020-10-1').format`, tDate('2020-10-1').format, 'yyyy-mm-dd hh:mi:ss.ms'],
			['tDate().format', _currTdate.format],
			['tDate().format', _currTdate.format, 'yyyy-mm-dd hh:mi:ss.ms'],
			['tDate().formatAsCn', _currTdate.formatAsCn],
			['tDate().formatAsCn', _currTdate.formatAsCn, true],
			['tDate().formatAsCn', _currTdate.formatAsCn, true, true],
			['tDate().formatAsCn', _currTdate.formatAsCn, false, true],
			['tDate().formatAsLunar', _currTdate.formatAsLunar],
			['tDate().formatAsLunar', _currTdate.formatAsLunar, false],
			['tDate().formatAsBh', _currTdate.formatAsBh],
			['tDate().formatAsWorld', _currTdate.formatAsWorld],
			['tDate().formatAsWorld', _currTdate.formatAsWorld, 'fr-ca'],
			['tDate().formatAsWorld', _currTdate.formatAsWorld, 'en-gb'],
			['tDate().formatAsWorld', _currTdate.formatAsWorld, 'ko-KR'],
			['tDate().getWeek', _currTdate.getWeek, 'zh'],
			['tDate().getWeek', _currTdate.getWeek, 'en'],
			['tDate().getWeekOfMonth', _currTdate.getWeekOfMonth, 'zh'],
			['tDate().getWeekOfMonth', _currTdate.getWeekOfMonth, 'en'],
			['tDate().getWeekOfYear', _currTdate.getWeekOfYear, 'zh'],
			['tDate().getWeekOfYear', _currTdate.getWeekOfYear, 'en'],
			['tDate().getQuarter', _currTdate.getQuarter, 'zh'],
			['tDate().getQuarter', _currTdate.getQuarter, 'en'],
			['tDate().getOffset', _currTdate.getOffset, 3, 'day'],
			['tDate().getOffset', _currTdate.getOffset, -3, 'day'],
			['tDate().getOffset', _currTdate.getOffset, 3, 'week'],
			['tDate().getOffset', _currTdate.getOffset, 3, 'month'],
			['tDate().getOffset', _currTdate.getOffset, 3, 'year'],
			['tDate().getDiff', _currTdate.getDiff, new Date(2020-12-31), 'day'],
			['tDate().getDiff', _currTdate.getDiff, '2020-12-31', 'day'],
			['tDate().getDiff', _currTdate.getDiff, 1609372800000, 'day'],
			['tDate().getDiff', _currTdate.getDiff, '2020-12-31', 'ms'],
			['tDate().getDiff', _currTdate.getDiff, '2020-12-31', 'second'],
			['tDate().getDiff', _currTdate.getDiff, '2020-12-31', 'minute'],
			['tDate().getDiff', _currTdate.getDiff, '2020-12-31', 'hour'],
			['tDate().getDiff', _currTdate.getDiff, '2020-12-31', 'day'],
			['tDate().getDiff', _currTdate.getDiff, '2020-12-31', 'week'],
			['tDate().getDiff', _currTdate.getDiff, '2020-12-31', 'month'],
			['tDate().getDiff', _currTdate.getDiff, '2020-12-31', 'year'],
			['tDate().toNumber', _currTdate.toNumber],
			['tDate().toNumber', _currTdate.toNumber, true],
			['tDate().toNumber', _currTdate.toNumber, true, 'yyyymmdd'],
			['tDate().toJson', _currTdate.toJson],
			['tDate().toJson', _currTdate.toJson, 'zh'],
			['tDate().toJson', _currTdate.toJson, 'en'],
			['tDate().toArr', _currTdate.toArr],
			['tDate().toArr', _currTdate.toArr, true]
		],
		[
			[`tVerifi.getRules`, tVerifi.getRules()],
			[`tVerifi.getRules`, tVerifi.exec('abc', '字符串', false)],
		],
		[
			[`tPinyin.groupByFirstLetter`, tPinyin.groupByFirstLetter, ['可', '测', '啊', '深']],
			[`tPinyin.groupByFirstLetter`, tPinyin.groupByFirstLetter, ['可', '测', '啊', '深'], true],
			[`tPinyin.getFirstLetter`, tPinyin.getFirstLetter, '可以']
		]
	]
};
